(define-fungible-token b2s-token u1000000000000000)
(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-constant err-not-token-owner (err u101))
(define-constant err-insufficient-balance (err u102))
(define-constant err-invalid-amount (err u103))
(define-constant err-already-claimed (err u104))
(define-data-var token-name (string-ascii 32) "Base2Stacks Token")
(define-data-var token-symbol (string-ascii 10) "B2S")
(define-data-var token-uri (optional (string-utf8 256)) (some u"https://base2stacks-tracker.vercel.app/token.json"))
(define-map daily-claims { tracker: principal, day: uint } { claimed: bool })
(define-map staked-balances { staker: principal } { amount: uint, staked-at: uint })
(define-data-var total-staked uint u0)
(define-read-only (get-name) (ok (var-get token-name)))
(define-read-only (get-symbol) (ok (var-get token-symbol)))
(define-read-only (get-decimals) (ok u6))
(define-read-only (get-balance (account principal)) (ok (ft-get-balance b2s-token account)))
(define-read-only (get-total-supply) (ok (ft-get-supply b2s-token)))
(define-read-only (get-token-uri) (ok (var-get token-uri)))
(define-read-only (get-staked-balance (staker principal))
  (default-to { amount: u0, staked-at: u0 } (map-get? staked-balances { staker: staker })))
(define-read-only (get-total-staked) (ok (var-get total-staked)))
(define-public (set-token-uri (new-uri (optional (string-utf8 256))))
  (begin (asserts! (is-eq tx-sender contract-owner) err-owner-only) (var-set token-uri new-uri) (ok true)))
(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
  (begin
    (asserts! (is-eq tx-sender sender) err-not-token-owner)
    (asserts! (> amount u0) err-invalid-amount)
    (try! (ft-transfer? b2s-token amount sender recipient))
    (match memo to-print (print to-print) 0x)
    (ok true)))
(define-public (mint (amount uint) (recipient principal))
  (begin (asserts! (is-eq tx-sender contract-owner) err-owner-only) (ft-mint? b2s-token amount recipient)))
(define-public (claim-daily-reward)
  (let ((claimer tx-sender) (current-day (/ block-height u144)) (reward-amount u5000000))
    (asserts! (is-none (map-get? daily-claims { tracker: claimer, day: current-day })) err-already-claimed)
    (map-set daily-claims { tracker: claimer, day: current-day } { claimed: true })
    (try! (ft-mint? b2s-token reward-amount claimer))
    (ok true)))
(define-public (stake (amount uint))
  (let ((staker tx-sender) (current-balance (ft-get-balance b2s-token staker)) (current-stake (get-staked-balance staker)))
    (asserts! (>= current-balance amount) err-insufficient-balance)
    (asserts! (> amount u0) err-invalid-amount)
    (try! (ft-transfer? b2s-token amount staker (as-contract tx-sender)))
    (map-set staked-balances { staker: staker } { amount: (+ (get amount current-stake) amount), staked-at: block-height })
    (var-set total-staked (+ (var-get total-staked) amount))
    (ok true)))
(define-public (unstake (amount uint))
  (let ((staker tx-sender) (current-stake (get-staked-balance staker)) (staked-amount (get amount current-stake)))
    (asserts! (>= staked-amount amount) err-insufficient-balance)
    (asserts! (> amount u0) err-invalid-amount)
    (try! (as-contract (ft-transfer? b2s-token amount tx-sender staker)))
    (map-set staked-balances { staker: staker } { amount: (- staked-amount amount), staked-at: (get staked-at current-stake) })
    (var-set total-staked (- (var-get total-staked) amount))
    (ok true)))
(begin (try! (ft-mint? b2s-token u400000000000000 contract-owner)))